language: php
php:
  - 5.6
  - 7.0
sudo: false
services:
  - docker
cache:
  directories:
    - $HOME/.composer/cache
before_script:
  - docker pull minhd/docker-pycsw
  - docker run -it -d -p 8000:8000 --name pycsw -v $TRAVIS_BUILD_DIR/resources/default.cfg:/opt/pycsw/default.cfg minhd/docker-pycsw
  - composer install
script:
  - php --version
  - docker --version
  - vendor/bin/phpunit --version
  - vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
